name: shell-commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multine script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import plataform
          print(plataform.processor())
        shell: python
